name: Work1 Edgar
on : [push]

jobs:
  build:
    runs-on: ubuntu-lastest
    container: node 16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: node app.js 